'use client';

import { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'ar';

type TranslationKey = string;

const translations: Record<Language, Record<TranslationKey, string>> = {
  en: {
    home: 'Home',
    about: 'About',
    collection: 'Collection',
    contact: 'Contact',
    signedInAs: 'Signed in as',
    signOut: 'Sign Out',
    myAccount: 'My Account',
    switchToArabic: 'العربية',
    switchToEnglish: 'English',
    capsule: 'Capsule 01 // The Arrival',
    heroTitle: 'KINETIC ARCHITECTURE.',
    heroDescription: 'Zero distractions. Pure physical expression. Engineered for the unseen elements of the modern environment.',
    exploreDrop: 'Explore the Drop',
    archiveAccess: 'Archive Access',
    vault: 'THE VAULT.',
    vaultDescription: 'Rare iterations. Unreleased colorways. Access granted for 48 hours.',
    materiaPrima: 'Materia Prima',
    sculptedToFit: 'Sculpted to fit',
    engineeredUnseen: 'Engineered for the Unseen Elements.',
    brandDescription: 'Pure physical expression. We bridge the gap between high-performance athletic wear and modern street aesthetics. Built for motion, designed for life.',
    premiumMaterials: 'Premium Materials',
    premiumMaterialsDescription: 'Sustainably sourced, built to endure.',
    globalShipping: 'Global Shipping',
    globalShippingDescription: 'Express delivery worldwide.',
    kineticFit: 'Kinetic Fit',
    kineticFitDescription: 'Unrestricted movement by design.',
    ourProducts: 'Our Products',
    drop01: 'Drop 01',
    coreCollection: 'Core Collection',
    archiveEmpty: 'Archive Empty. No products available.',
    collectionResults: 'Result',
    collectionResultsPlural: 'Results',
    searchCollection: 'Search collection...',
    clear: 'Clear',
    sort: 'Sort',
    relevance: 'Relevance',
    priceLow: 'Price: Low to High',
    priceHigh: 'Price: High to Low',
    newest: 'Newest',
    noProductsMatched: 'No products matched your search criteria.',
    tryAnotherSearch: 'Try another search',
    loading: 'Loading...',
    loadingMedia: 'Loading Media //',
    nothingToSee: 'Nothing to see here',
    taxesIncluded: 'Taxes included.',
    selectSize: 'Select Size',
    sizeGuide: 'Size Guide',
    sizesUnavailable: 'Sizes Unavailable',
    addToCart: 'Add to Cart',
    processing: 'Processing...',
    freeGlobalShipping: 'Free Global Shipping',
    freeReturns: 'Free Returns',
    description: 'Description',
    details: 'Details',
    shoppingBag: 'Shopping Bag',
    item: 'Item',
    items: 'Items',
    bagEmpty: 'Your shopping bag is currently empty.',
    exploreCollection: 'Explore Collection',
    noImage: 'No Image',
    size: 'Size',
    remove: 'Remove',
    deliveryInformation: 'Delivery Information',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    stateProvince: 'State / Province',
    cityAddress: 'City / Address',
    homeDelivery: 'Home Delivery',
    pickupPoint: 'Pick-up Point',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    pickUp: 'Pick-up',
    extraWeight: 'Extra Weight Surcharge',
    total: 'Total',
    completeCheckout: 'Complete Checkout',
    paymentUponDelivery: 'Payment collected upon delivery',
    signIn: 'Sign In',
    signInDescription: 'Access the archive. View your order history, track shipments, and manage your preferences.',
    emailAddress: 'Email Address',
    password: 'Password',
    accessing: 'Accessing...',
    accessAccount: 'Access Account',
    invalidCredentials: 'Invalid email or password.',
    forgotPassword: 'Forgot Password?',
    createAccount: 'Create Account',
    creatingAccount: 'Creating Account...',
    signUp: 'Sign Up',
    signInInstead: 'Sign In Instead',
    accountCreated: 'Account created! Please sign in.',
    theVision: 'The Vision',
    ourDirective: 'Our Directive',
    theStandard: 'The Standard',
    clientServices: 'Client Services',
    contactDescription: 'For inquiries regarding the archive, recent orders, or general styling questions, please submit a request below. Our concierge team operates globally and responds within 24 hours.',
    headquarters: 'Headquarters',
    directContact: 'Direct Contact',
    yourMessage: 'Your Message',
    submitInquiry: 'Submit Inquiry',
    unlockDrops: 'Unlock Exclusive Drops.',
    newsletterDescription: 'Subscribe to get early access to new collections, restocks, and exclusive Athletix deals.',
    emailPlaceholder: 'Enter your email address',
    subscribe: 'Subscribe',
    shop: 'Shop',
    support: 'Support',
    legal: 'Legal',
    mensCollection: "Men's Collection",
    womensCollection: "Women's Collection",
    equipment: 'Equipment',
    newArrivals: 'New Arrivals',
    trackOrder: 'Track Order',
    returns: 'Returns & Exchanges',
    faq: 'FAQ',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    shippingPolicy: 'Shipping Policy',
    allRightsReserved: 'All rights reserved.',
    category: 'Category',
    uncategorized: 'Uncategorized',
    mayYouLike: 'You May Like',
    engineeredMovement: 'Engineered for modern movement.',
    standardFit: 'Standard fit for a relaxed, easy feel.',
    machineWash: 'Machine wash cold, lay flat to dry.',
    productId: 'Product ID',
    addressRequired: 'Please select a province and enter your address.',
    phoneRequired: 'Please enter a valid 10-digit phone number.',
    orderSubmitted: 'Order submitted successfully!',
    orderError: 'An error occurred while submitting your order. Please try again.',
    completeLook: 'Complete The Look',
    viewArchive: 'View Archive',
    noRelatedProducts: 'No related products available.',
    aboutIntro: 'was born from a desire to bridge the gap between high-performance technical wear and minimalist urban architecture. We do not just design garments; we engineer them.',
    aboutCraft: 'Every silhouette is meticulously crafted using proprietary textiles to ensure fluidity, durability, and a striking visual presence. We stripped away the noise, the logos, and the excess, leaving only what is essential for the modern environment.',
    aboutDirective: 'To redefine the modern uniform through kinetic architecture and uncompromising material quality.',
    qualityAssurance: 'Quality Assurance',
    qualityDescription: 'We meticulously select and vet each product to ensure it meets our stringent quality standards.',
    convenience: 'Convenience',
    convenienceDescription: 'With our user-friendly interface and hassle-free ordering process, shopping has never been easier.',
    customerService: 'Exceptional Customer Service',
    customerServiceDescription: 'Our team of dedicated professionals is here to assist you, ensuring your satisfaction is our top priority.',
    buyNow: 'Buy Now',
    cancel: 'Cancel',
  },
  ar: {
    home: 'الرئيسية',
    about: 'من نحن',
    collection: 'المجموعة',
    contact: 'اتصل بنا',
    signedInAs: 'تم تسجيل الدخول باسم',
    signOut: 'تسجيل الخروج',
    myAccount: 'حسابي',
    switchToArabic: 'العربية',
    switchToEnglish: 'English',
    capsule: 'الإصدار 01 // الوصول',
    heroTitle: 'هندسة الحركة.',
    heroDescription: 'بلا تشتيت. تعبير جسدي خالص. مصمم للعناصر غير المرئية في البيئة الحديثة.',
    exploreDrop: 'اكتشف الإصدار',
    archiveAccess: 'دخول الأرشيف',
    vault: 'الخزنة.',
    vaultDescription: 'تصاميم نادرة. ألوان لم تصدر بعد. الدخول متاح لمدة 48 ساعة.',
    materiaPrima: 'المادة الخام',
    sculptedToFit: 'مصمم ليناسبك',
    engineeredUnseen: 'مصمم للعناصر غير المرئية.',
    brandDescription: 'تعبير جسدي خالص. نصل بين الملابس الرياضية عالية الأداء وجماليات الشارع الحديثة. صُمم للحركة وللحياة.',
    premiumMaterials: 'خامات فاخرة',
    premiumMaterialsDescription: 'مصادر مستدامة، مصممة لتدوم.',
    globalShipping: 'شحن عالمي',
    globalShippingDescription: 'توصيل سريع حول العالم.',
    kineticFit: 'ملاءمة حركية',
    kineticFitDescription: 'حرية حركة بلا قيود بتصميم مدروس.',
    ourProducts: 'منتجاتنا',
    drop01: 'الإصدار 01',
    coreCollection: 'المجموعة الأساسية',
    archiveEmpty: 'الأرشيف فارغ. لا توجد منتجات متاحة.',
    collectionResults: 'نتيجة',
    collectionResultsPlural: 'نتائج',
    searchCollection: 'ابحث في المجموعة...',
    clear: 'مسح',
    sort: 'ترتيب',
    relevance: 'الأكثر صلة',
    priceLow: 'السعر: من الأقل إلى الأعلى',
    priceHigh: 'السعر: من الأعلى إلى الأقل',
    newest: 'الأحدث',
    noProductsMatched: 'لم يتم العثور على منتجات تطابق بحثك.',
    tryAnotherSearch: 'جرّب بحثًا آخر',
    loading: 'جار التحميل...',
    loadingMedia: 'جار تحميل الوسائط //',
    nothingToSee: 'لا شيء لعرضه هنا',
    taxesIncluded: 'الضرائب مشمولة.',
    selectSize: 'اختر المقاس',
    sizeGuide: 'دليل المقاسات',
    sizesUnavailable: 'المقاسات غير متاحة',
    addToCart: 'أضف إلى السلة',
    processing: 'جار المعالجة...',
    freeGlobalShipping: 'شحن عالمي مجاني',
    freeReturns: 'إرجاع مجاني',
    description: 'الوصف',
    details: 'التفاصيل',
    shoppingBag: 'سلة التسوق',
    item: 'منتج',
    items: 'منتجات',
    bagEmpty: 'سلة التسوق فارغة حاليًا.',
    exploreCollection: 'اكتشف المجموعة',
    noImage: 'لا توجد صورة',
    size: 'المقاس',
    remove: 'حذف',
    deliveryInformation: 'معلومات التوصيل',
    fullName: 'الاسم الكامل',
    phoneNumber: 'رقم الهاتف',
    stateProvince: 'الولاية',
    cityAddress: 'المدينة / العنوان',
    homeDelivery: 'توصيل إلى المنزل',
    pickupPoint: 'نقطة الاستلام',
    subtotal: 'المجموع الفرعي',
    shipping: 'الشحن',
    pickUp: 'الاستلام',
    extraWeight: 'رسوم الوزن الإضافي',
    total: 'الإجمالي',
    completeCheckout: 'إتمام الطلب',
    paymentUponDelivery: 'الدفع عند التوصيل',
    signIn: 'تسجيل الدخول',
    signInDescription: 'ادخل إلى الأرشيف. راجع سجل طلباتك، وتتبع الشحنات، وأدر تفضيلاتك.',
    emailAddress: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    accessing: 'جار الدخول...',
    accessAccount: 'دخول الحساب',
    invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    forgotPassword: 'هل نسيت كلمة المرور؟',
    createAccount: 'إنشاء حساب',
    creatingAccount: 'جار إنشاء الحساب...',
    signUp: 'إنشاء حساب',
    signInInstead: 'تسجيل الدخول بدلًا من ذلك',
    accountCreated: 'تم إنشاء الحساب! يرجى تسجيل الدخول.',
    theVision: 'الرؤية',
    ourDirective: 'توجهنا',
    theStandard: 'المعيار',
    clientServices: 'خدمة العملاء',
    contactDescription: 'للاستفسار عن الأرشيف أو الطلبات الأخيرة أو أسئلة التنسيق، أرسل طلبًا أدناه. يعمل فريقنا عالميًا ويرد خلال 24 ساعة.',
    headquarters: 'المقر الرئيسي',
    directContact: 'اتصال مباشر',
    yourMessage: 'رسالتك',
    submitInquiry: 'إرسال الاستفسار',
    unlockDrops: 'اكتشف الإصدارات الحصرية.',
    newsletterDescription: 'اشترك لتحصل على وصول مبكر إلى المجموعات الجديدة وإعادة التوفر وعروض Athletix الحصرية.',
    emailPlaceholder: 'أدخل بريدك الإلكتروني',
    subscribe: 'اشتراك',
    shop: 'تسوق',
    support: 'الدعم',
    legal: 'قانوني',
    mensCollection: 'مجموعة الرجال',
    womensCollection: 'مجموعة النساء',
    equipment: 'المعدات',
    newArrivals: 'وصل حديثًا',
    trackOrder: 'تتبع الطلب',
    returns: 'الإرجاع والاستبدال',
    faq: 'الأسئلة الشائعة',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الخدمة',
    shippingPolicy: 'سياسة الشحن',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    category: 'الفئة',
    uncategorized: 'غير مصنف',
    mayYouLike: 'قد يعجبك أيضًا',
    engineeredMovement: 'مصمم للحركة العصرية.',
    standardFit: 'قصة قياسية لراحة واسترخاء أكبر.',
    machineWash: 'يُغسل بماء بارد ويُجفف بشكل مسطح.',
    productId: 'معرف المنتج',
    addressRequired: 'يرجى اختيار الولاية وإدخال العنوان.',
    phoneRequired: 'يرجى إدخال رقم هاتف صحيح مكون من 10 أرقام.',
    orderSubmitted: 'تم إرسال الطلب بنجاح!',
    orderError: 'حدث خطأ أثناء إرسال الطلب. يرجى المحاولة مرة أخرى.',
    completeLook: 'أكمل الإطلالة',
    viewArchive: 'عرض الأرشيف',
    noRelatedProducts: 'لا توجد منتجات ذات صلة.',
    aboutIntro: 'نشأت Athletix من رغبة في سد الفجوة بين الملابس التقنية عالية الأداء والهندسة الحضرية البسيطة. نحن لا نصمم الملابس فحسب، بل نهندسها.',
    aboutCraft: 'كل تصميم يُصنع بعناية باستخدام أقمشة خاصة لضمان المرونة والمتانة والحضور البصري اللافت. أزلنا الضجيج والشعارات والزائد، وأبقينا فقط ما هو أساسي للبيئة الحديثة.',
    aboutDirective: 'إعادة تعريف الزي الحديث من خلال هندسة الحركة وجودة الخامات التي لا تقبل التنازل.',
    qualityAssurance: 'ضمان الجودة',
    qualityDescription: 'نختار كل منتج ونتحقق منه بعناية لضمان توافقه مع معايير الجودة الصارمة.',
    convenience: 'الراحة',
    convenienceDescription: 'بفضل واجهتنا السهلة وعملية الطلب البسيطة، أصبح التسوق أسهل من أي وقت مضى.',
    customerService: 'خدمة عملاء استثنائية',
    customerServiceDescription: 'فريقنا من المحترفين هنا لمساعدتك، ورضاك هو أولويتنا.',
    buyNow: 'اشترِ الآن',
    cancel: 'إلغاء',
  },
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  const direction = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    const savedLanguage = window.localStorage.getItem('language');
    if (savedLanguage === 'ar' || savedLanguage === 'en') {
      setLanguageState(savedLanguage);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
    window.localStorage.setItem('language', language);
  }, [language, direction]);

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage: setLanguageState,
        toggleLanguage: () => setLanguageState((current) => (current === 'en' ? 'ar' : 'en')),
        t: (key) => translations[language][key],
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}